
on: [push, pull_request]
name: CI
jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: test
        run: |
          go install golang.org/x/lint/golint@latest &&
          go install github.com/go-bindata/go-bindata/...@latest &&
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          go generate &&
          make
